spring:
  application:
    name: ERP System
  datasource:
    url: ${DB_URL:jdbc:postgresql://crpdb.cvykai2co4xw.eu-north-1.rds.amazonaws.com:5432/crpdb}
    username: ${DB_USERNAME:Titanic}
    password: ${DB_PASSWORD:q9Cm55T19G9kXHSuGSQG}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
