spring:
  application:
    name: SE_FINAL_Sales
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/se_final_sales}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
