spring.application.name=admin

spring.datasource.url=${DB_URL:jdbc:postgresql://crpdb.cvykai2co4xw.eu-north-1.rds.amazonaws.com:5432/crpdb}
spring.datasource.username=${DB_USERNAME:Titanic}
spring.datasource.password=${DB_PASSWORD:q9Cm55T19G9kXHSuGSQG}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${ADMIN_PORT:8081}

spring.mvc.problemdetails.enabled=true
logging.level.org.flywaydb=INFO

app.lockout.max-attempts=5
app.lockout.duration-minutes=15

app.erp.base-url=${ERP_BASE_URL:http://localhost:8080}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
