spring.application.name=admin

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/se_final_admin}
spring.datasource.username=${DB_USER:ahmad}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

server.port=8080
spring.mvc.problemdetails.enabled=true
logging.level.org.flywaydb=INFO
